
project_id = "gxkdlylqmwwlhyyqlwfm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[[edge_functions.function]]
name = "update-sharepoint-excel"
verify_jwt = false

[[edge_functions.function]]
name = "send-to-zapier"
verify_jwt = false

